version: '3.9'

services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=12345567'
      - 'POSTGRES_USER=messenger'
    ports:
      - '5432:5432'
    volumes: # volume used to persist data
      - pgdata:/var/lib/postgresql/data
    networks:
      - localhost
    restart: always

volumes: # volume creation
  pgdata: {}

networks:
  localhost:
    driver: bridge